version: '3.3'

services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backup:/postgresql-backup
    ports:
      - 5432:5432
