global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: 'service_monitoring'
    scrape_interval: 5s
    static_configs:
      - targets: ["nodeexporter:9100"]
