---
elasticsearch:
  hosts:
    el-instance:
      ansible_connection: ssh
      ansible_host: 51.250.20.30
      ansible_user: reist
filebeat:
  hosts:
    filebeat-instance:
      ansible_connection: ssh
      ansible_host: 51.250.107.159
      ansible_user: reist
kibana:
  hosts:
    kibana-instance:
      ansible_connection: ssh
      ansible_host: 51.250.109.32
      ansible_user: reist