{
 "title": "DevOps-base",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(instance)(irate(node_cpu_seconds_total{mode='idle'}[1m]))",
     "legendFormat": "1min avg"
    },
    {
     "expr": "avg by(instance)(irate(node_cpu_seconds_total{mode='idle'}[5m]))",
     "legendFormat": "5min avg"
    },
    {
     "expr": "avg by(instance)(irate(node_cpu_seconds_total{mode='idle'}[15m]))",
     "legendFormat": "15min avg"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs\"} * 100",
     "legendFormat": "Disk Space"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes / on (instance) node_memory_MemTotal_bytes * 100",
     "legendFormat": "Node Memory"
    }
   ]
  },
  {
   "title": "Cpu",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance)(irate(node_cpu_seconds_total{mode='idle'}[1m])))",
     "legendFormat": "Node Cpu Usage"
    }
   ]
  }
 ]
}